[workspace]
authors = ["Aleksandras Voicikas <aleksandrasv@neurotechnology.com>"]
channels = ["conda-forge"]
name = "Downloads"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pip = ">=25.1.1,<26"
